---
abstract: 'the wxPerl demo'
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wx-Demo
no_index:
  directory:
    - t
    - inc
    - lib/Wx/DemoModules/files/
requires:
  Class::Accessor::Fast: 0.2
  File::Slurp: 0.01
  File::Spec: 0.8
  File::chdir: 0.06
  IO::Scalar: 2
  Module::Pluggable: 3.1
  UNIVERSAL::require: 0.1
  Wx: 0.64
resources:
  homepage: http://wxperl.sourceforge.net/
  repository: https://wxperl.svn.sourceforge.net/svnroot/wxperl/wxDemo/trunk
  x_MailingList: wxperl-users@perl.org
version: 0.22
